"""add_bookmark_tables

Revision ID: 347b8cb81db7
Revises: de59ef35f297
Create Date: 2025-11-27 19:52:36.002865

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "347b8cb81db7"
down_revision: Union[str, Sequence[str], None] = "de59ef35f297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
