"""Add Message table for peer messaging

Revision ID: 3c7733ba5c52
Revises: 347b8cb81db7
Create Date: 2025-11-27 21:04:14.159429

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3c7733ba5c52"
down_revision: Union[str, Sequence[str], None] = "347b8cb81db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
