"""add_user_profile

Revision ID: 4e742b979bdd
Revises: 81e660d3fa35
Create Date: 2025-11-07 17:26:56.509586

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e742b979bdd"
down_revision: Union[str, Sequence[str], None] = "81e660d3fa35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("user", sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column(
        "user", sa.Column("institution", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("user", sa.Column("majors", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("minors", sa.JSON(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "profile_completed", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_completed")
    op.drop_column("user", "minors")
    op.drop_column("user", "majors")
    op.drop_column("user", "institution")
    op.drop_column("user", "age")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
