"""add program place and trip models

Revision ID: 81e660d3fa35
Revises: f6018f701c48
Create Date: 2025-10-07 10:52:30.136651

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e660d3fa35"
down_revision: Union[str, Sequence[str], None] = "f6018f701c48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_place_category"), "place", ["category"], unique=False)
    op.create_index(op.f("ix_place_city"), "place", ["city"], unique=False)
    op.create_index(op.f("ix_place_country"), "place", ["country"], unique=False)
    op.create_index(op.f("ix_place_name"), "place", ["name"], unique=False)
    op.create_table(
        "study_abroad_program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("program_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("institution", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("housing_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_study_abroad_program_city"), "study_abroad_program", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_study_abroad_program_country"), "study_abroad_program", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_study_abroad_program_program_name"),
        "study_abroad_program",
        ["program_name"],
        unique=False,
    )
    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trip_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_country"), "trip", ["country"], unique=False)
    op.create_index(op.f("ix_trip_destination"), "trip", ["destination"], unique=False)
    op.create_table(
        "course_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("course_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["study_abroad_program.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_review_program_id"), "course_review", ["program_id"], unique=False
    )
    op.create_index(op.f("ix_course_review_user_id"), "course_review", ["user_id"], unique=False)
    op.create_table(
        "place_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_place_review_place_id"), "place_review", ["place_id"], unique=False)
    op.create_index(op.f("ix_place_review_user_id"), "place_review", ["user_id"], unique=False)
    op.create_table(
        "program_housing_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("housing_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["study_abroad_program.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_program_housing_review_program_id"),
        "program_housing_review",
        ["program_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_program_housing_review_user_id"),
        "program_housing_review",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "program_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["study_abroad_program.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_program_review_program_id"), "program_review", ["program_id"], unique=False
    )
    op.create_index(op.f("ix_program_review_user_id"), "program_review", ["user_id"], unique=False)
    op.create_table(
        "trip_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_review_trip_id"), "trip_review", ["trip_id"], unique=False)
    op.create_index(op.f("ix_trip_review_user_id"), "trip_review", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_review_user_id"), table_name="trip_review")
    op.drop_index(op.f("ix_trip_review_trip_id"), table_name="trip_review")
    op.drop_table("trip_review")
    op.drop_index(op.f("ix_program_review_user_id"), table_name="program_review")
    op.drop_index(op.f("ix_program_review_program_id"), table_name="program_review")
    op.drop_table("program_review")
    op.drop_index(op.f("ix_program_housing_review_user_id"), table_name="program_housing_review")
    op.drop_index(op.f("ix_program_housing_review_program_id"), table_name="program_housing_review")
    op.drop_table("program_housing_review")
    op.drop_index(op.f("ix_place_review_user_id"), table_name="place_review")
    op.drop_index(op.f("ix_place_review_place_id"), table_name="place_review")
    op.drop_table("place_review")
    op.drop_index(op.f("ix_course_review_user_id"), table_name="course_review")
    op.drop_index(op.f("ix_course_review_program_id"), table_name="course_review")
    op.drop_table("course_review")
    op.drop_index(op.f("ix_trip_destination"), table_name="trip")
    op.drop_index(op.f("ix_trip_country"), table_name="trip")
    op.drop_table("trip")
    op.drop_index(op.f("ix_study_abroad_program_program_name"), table_name="study_abroad_program")
    op.drop_index(op.f("ix_study_abroad_program_country"), table_name="study_abroad_program")
    op.drop_index(op.f("ix_study_abroad_program_city"), table_name="study_abroad_program")
    op.drop_table("study_abroad_program")
    op.drop_index(op.f("ix_place_name"), table_name="place")
    op.drop_index(op.f("ix_place_country"), table_name="place")
    op.drop_index(op.f("ix_place_city"), table_name="place")
    op.drop_index(op.f("ix_place_category"), table_name="place")
    op.drop_table("place")
    # ### end Alembic commands ###
