"""Add study abroad status fields to User

Revision ID: ebe7bd8731c4
Revises: 3c7733ba5c52
Create Date: 2025-11-27 21:22:18.211364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe7bd8731c4"
down_revision: Union[str, Sequence[str], None] = "3c7733ba5c52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("study_abroad_status", sa.String(), nullable=True))
    op.add_column("user", sa.Column("program_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("program_city", sa.String(), nullable=True))
    op.add_column("user", sa.Column("program_country", sa.String(), nullable=True))
    op.add_column("user", sa.Column("program_term", sa.String(), nullable=True))
    op.add_column(
        "user", sa.Column("onboarding_completed", sa.Boolean(), nullable=True, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "onboarding_completed")
    op.drop_column("user", "program_term")
    op.drop_column("user", "program_country")
    op.drop_column("user", "program_city")
    op.drop_column("user", "program_name")
    op.drop_column("user", "study_abroad_status")
    # ### end Alembic commands ###
